module.exports = {
    content: [
      './src/**/*.{html,js,jsx,ts,tsx}',
    ],
    darkMode: 'class',
    theme: {
      extend: {
        colors: {
          'inverse-primary': '#7748a6',
          'on-tertiary': '#57124d',
          'on-primary-container': '#c794f8',
          'on-tertiary-container': '#e48dce',
          'primary-container': '#552583',
          'on-secondary-fixed-variant': '#5e4100',
          'secondary-fixed': '#ffdea9',
          'on-surface': '#e7e1e6',
          'on-primary-fixed-variant': '#5e2e8c',
          'tertiary-fixed-dim': '#fface8',
          'on-primary': '#461274',
          'surface-container-high': '#2c292d',
          'error-container': '#93000a',
          'surface-bright': '#3b383d',
          'on-secondary-fixed': '#271900',
          'on-tertiary-fixed-variant': '#722b65',
          'surface-dim': '#151317',
          'surface-container-highest': '#373438',
          'on-secondary-container': '#583c00',
          'tertiary-container': '#68225c',
          'primary-fixed': '#f0dbff',
          'secondary': '#ffbe3c',
          'surface': '#151317',
          'tertiary': '#fface8',
          'on-secondary': '#422d00',
          'surface-tint': '#ddb8ff',
          'secondary-fixed-dim': '#ffba29',
          'inverse-surface': '#e7e1e6',
          'primary-fixed-dim': '#ddb8ff',
          'outline': '#978d9c',
          'inverse-on-surface': '#322f34',
          'surface-container-lowest': '#0f0d11',
          'error': '#ffb4ab',
          'on-surface-variant': '#cec3d2',
          'tertiary-fixed': '#ffd7f0',
          'secondary-container': '#e3a200',
          'surface-container-low': '#1d1b1f',
          'on-error': '#690005',
          'on-primary-fixed': '#2c0051',
          'primary': '#ddb8ff',
          'on-tertiary-fixed': '#3a0033',
          'outline-variant': '#4b4450',
          'on-error-container': '#ffdad6',
          'on-background': '#e7e1e6',
          'surface-variant': '#373438',
          'background': '#151317',
          'surface-container': '#211f23',
        },
        fontFamily: {
          headline: ['Epilogue', 'sans-serif'],
          body: ['Manrope', 'sans-serif'],
          label: ['Manrope', 'sans-serif'],
        },
        borderRadius: {
          DEFAULT: '0px',
          lg: '0px',
          xl: '0px',
          full: '9999px',
        },
        keyframes: {
          reveal: {
            '0%': { opacity: '1' },
            '50%': { opacity: '0.5' },
            '100%': { opacity: '0' },
          },
          slide: {
            '0%': { transform: 'translateX(0)' },
            '100%': { transform: 'translateX(-50%)' },
          },
        },
        animation: {
          reveal: 'reveal 3s ease-in-out infinite',
          slide: 'slide 20s linear infinite',
          'slide-reverse': 'slide 20s linear infinite reverse',
        },
      },
    },
    plugins: [],
  };
  