// Route path constants — no imports, no circular dependencies
export const LOGINSTORE = "/store/login";
export const REGISTERSTORE = "/store/register";
export const HOME = "/";
export const ABOUT = "/about";
export const NEWS = "/news";
export const STORE = "/store";
export const DASHBOARD = "/dashboard";
export const ADMIN = "/dashboard/admins";
export const PRODUCT = "/dashboard/products";
export const CATEGORIES = "/dashboard/categories";
export const SUBCATEGORIES = "/dashboard/sub-categories";
export const ORDERS = "/dashboard/orders";
export const CREATE_ARTICLES = "/dashboard/news/create";
export const ARTICLES_CONTENT = "/dashboard/news";
export const CART = "/store/cart";
export const CHECKOUT = "/store/checkout";
export const WISHLIST = "/store/wishlist";
export const ALLPRODUCTS = "/store/products";
export const ALL_CATEGORIES = "/store/categories";
export const PRODUCT_DETAIL = (id) => `/store/product-detail/${id}`;
export const PRODUCT_CREATE = "/dashboard/products/create";
export const TEXT_FILL_LOADING = "/text-fill-loading";
export const ADMIN_CREATE = "/dashboard/admins/new";
export const USER_DETAIL = "/dashboard/users";
export const PLAYERS = "/dashboard/players";
export const TEAMS = "/dashboard/teams";
export const PLAYERS_CREATE = "/dashboard/players/new";
export const PLAYERS_EDIT = (id) => `/dashboard/players/edit/${id}`;
export const TEAMS_CREATE = "/dashboard/teams/new";
export const LOGIN = "/login";
export const MATCH_DETAIL = "/match-details/:id";
